version: '3.7'

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
  backend:
    image: fridgify/fridgify:develop-latest
    ports:
      - 9000:9000
    volumes:
      - /home/fridgify/static_files/production/:/fridgify/Fridgify_Backend/static/
    depends_on:
      - db
volumes:
  postgres_data: